<flow MovieStatsFlow step join> failed:
    Internal error
Traceback (most recent call last):
  File "/Users/viveckh/opt/miniconda3/envs/metaflow_MovieStatsFlow_osx-64_2d101912e3f1df445fe4596cc72530fa1e5ae4cc/lib/python3.7/site-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/Users/viveckh/opt/miniconda3/envs/metaflow_MovieStatsFlow_osx-64_2d101912e3f1df445fe4596cc72530fa1e5ae4cc/lib/python3.7/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/Users/viveckh/opt/miniconda3/envs/metaflow_MovieStatsFlow_osx-64_2d101912e3f1df445fe4596cc72530fa1e5ae4cc/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen(/Users/viveckh/opt/miniconda3/envs/metaflow_MovieStatsFlow_osx-64_2d101912e3f1df445fe4596cc72530fa1e5ae4cc/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libopenblas.dylib
  Referenced from: /Users/viveckh/opt/miniconda3/envs/metaflow_MovieStatsFlow_osx-64_2d101912e3f1df445fe4596cc72530fa1e5ae4cc/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/tmpaxa8a7ua/metaflow/cli.py", line 853, in main
    start(auto_envvar_prefix='METAFLOW', obj=state)
  File "/Users/viveckh/opt/miniconda3/envs/metaflow_MovieStatsFlow_osx-64_2d101912e3f1df445fe4596cc72530fa1e5ae4cc/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(args, kwargs)
  File "/Users/viveckh/opt/miniconda3/envs/metaflow_MovieStatsFlow_osx-64_2d101912e3f1df445fe4596cc72530fa1e5ae4cc/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/viveckh/opt/miniconda3/envs/metaflow_MovieStatsFlow_osx-64_2d101912e3f1df445fe4596cc72530fa1e5ae4cc/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/viveckh/opt/miniconda3/envs/metaflow_MovieStatsFlow_osx-64_2d101912e3f1df445fe4596cc72530fa1e5ae4cc/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, ctx.params)
  File "/Users/viveckh/opt/miniconda3/envs/metaflow_MovieStatsFlow_osx-64_2d101912e3f1df445fe4596cc72530fa1e5ae4cc/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(args, kwargs)
  File "/Users/viveckh/opt/miniconda3/envs/metaflow_MovieStatsFlow_osx-64_2d101912e3f1df445fe4596cc72530fa1e5ae4cc/lib/python3.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, args, kwargs)
  File "/tmp/tmpaxa8a7ua/metaflow/cli.py", line 430, in step
    max_user_code_retries)
  File "/tmp/tmpaxa8a7ua/metaflow/task.py", line 373, in run_step
    self._exec_step_function(step_func, input_obj)
  File "/tmp/tmpaxa8a7ua/metaflow/task.py", line 49, in _exec_step_function
    step_function(input_obj)
  File "tutorial_flow.py", line 105, in join
    for inp in inputs}
  File "tutorial_flow.py", line 105, in <dictcomp>
    for inp in inputs}
  File "/tmp/tmpaxa8a7ua/metaflow/flowspec.py", line 122, in __getattr__
    x = self._datastore[name]
  File "/tmp/tmpaxa8a7ua/metaflow/datastore/datastore.py", line 571, in __getitem__
    return self._load_object(self.objects[var])
  File "/tmp/tmpaxa8a7ua/metaflow/datastore/datastore.py", line 453, in _load_object
    return pickle.loads(blob)
  File "/Users/viveckh/opt/miniconda3/envs/metaflow_MovieStatsFlow_osx-64_2d101912e3f1df445fe4596cc72530fa1e5ae4cc/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/Users/viveckh/opt/miniconda3/envs/metaflow_MovieStatsFlow_osx-64_2d101912e3f1df445fe4596cc72530fa1e5ae4cc/lib/python3.7/site-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "/Users/viveckh/opt/miniconda3/envs/metaflow_MovieStatsFlow_osx-64_2d101912e3f1df445fe4596cc72530fa1e5ae4cc/bin/python",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.4" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: dlopen(/Users/viveckh/opt/miniconda3/envs/metaflow_MovieStatsFlow_osx-64_2d101912e3f1df445fe4596cc72530fa1e5ae4cc/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libopenblas.dylib
  Referenced from: /Users/viveckh/opt/miniconda3/envs/metaflow_MovieStatsFlow_osx-64_2d101912e3f1df445fe4596cc72530fa1e5ae4cc/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so
  Reason: image not found


